### PR TITLE
Fb legal text

### PR DESCRIPTION
**Pull request by joscha-st**
This pr include the 

- imprint
- privacy policy
- and AGB

Both, as react pages and in the dictionary.

### CODE REVIEW

**Comment by LukasStrickler** [comment]
- add Contact for mock listing of support etc etc 
- add mock about page

**Review by LukasStrickler — CHANGES_REQUESTED** [review]
change routing names to englisch, all routing is in eng in the project

**Comment by joscha-st** [comment]
> change routing names to englisch, all routing is in eng in the project

I created the routing specifically as per the expectation to fit the already existing links

**Comment by LukasStrickler** [comment]
> > change routing names to englisch, all routing is in eng in the project
> 
> I created the routing specifically as per the communicated expectation to fit the already existing links

good job! i still think we should have routing names in eng to be consistent if not then pls overturn this @Timbo003

**Comment by joscha-st** [comment]
> > > change routing names to englisch, all routing is in eng in the project
> > 
> > 
> > I created the routing specifically as per the communicated expectation to fit the already existing links
> 
> good job! i still think we should have routing names in eng to be consistent if not then pls overturn this @Timbo003 if @Timbo003 agrees, then also pls change the links in the footer

In general, I defo agree, I can also change it but pls let's do this in a new PR, it's also relevant in my other PR, and otherwise it'll lead to merge conflicts again.

**Review by LukasStrickler — APPROVED** [review]

**Pull request merged**
