### PR TITLE
writeup structure & paper parts

### PR DESCRIPTION
**Pull request by sternlis**
#41 

Link: https://hsludwigshafen.sharepoint.com/:w:/s/SoftwareEngineeringProjekt865/EcgjhdzevbRAkr6gqvvzy1ABsOTqL7mje5AnPNf5V-ge4g?e=B4fPpA 

#42 

Link: https://hsludwigshafen.sharepoint.com/:w:/s/SoftwareEngineeringProjekt865/EYjhf5eMs3hOlS7y6xVIGjcBxuqiS0YpxdCtxyEoraXMzA?e=1XYNWf

#45 

Link: https://hsludwigshafen.sharepoint.com/:w:/s/SoftwareEngineeringProjekt865/EfaEpZBmpjBHoh5-C1npytUBjHapULAbrv6aLuaysFHUCA?e=CcXtjm

#44 

Link: https://hsludwigshafen.sharepoint.com/:w:/s/SoftwareEngineeringProjekt865/EQmkiabMZ1tAqj1Yelkz-jEBu4aoiU4LXo7a9wm9DXDK-w?e=rEq5da

#48 #57 

Link: https://hsludwigshafen.sharepoint.com/:w:/s/SoftwareEngineeringProjekt865/EbdfQnk6u91Mnk7JyisImzEBYNajvlv9TFpWNboUmwBVhQ?e=maJYSb

#47 

Link: https://hsludwigshafen.sharepoint.com/:w:/s/SoftwareEngineeringProjekt865/ER47OD5WT11PocV7H5pNtDcBerzwOWjL4qQ9O3mpueHdXQ?e=zL7sct

### CODE REVIEW

**Review by LukasStrickler — CHANGES_REQUESTED** [review]
changes in word files

**Review by Timbo003 — APPROVED** [review]

**Review by paulKlarer — APPROVED** [review]
looks good

**Review by LukasStrickler — APPROVED** [review]

**Review by joscha-st — APPROVED** [review]

**Review by joscha-st — CHANGES_REQUESTED** [review]
changes reuested as per comments in docs.

Außerdem sollten wir eine einheitliche Zeitform waren, wenn wir über das abgeschlossene Projekt reden. Momentan ist es gemischt.

**Review by joscha-st — APPROVED** [review]
looks good now 👍

**Pull request merged**
